"""Prototype_SIES.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v0Wool2J0PCSi5TFlhvF2037TyVp5lSg
"""

pip install rapidfuzz

pip install langdetect

import pandas as pd
import numpy as np

from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.cluster import DBSCAN

from rapidfuzz import fuzz
from langdetect import detect

import warnings
warnings.filterwarnings("ignore")

# Replace with your file name if different
df = pd.read_csv("/content/sample_data/ultra_complex_multilingual_dataset.csv")

print("Dataset Shape:", df.shape)
df.head()

def preprocess_text(text):
    if pd.isnull(text):
        return ""
    return str(text).strip()

# Clean columns
df["name"] = df["name"].apply(preprocess_text)
df["description"] = df["description"].apply(preprocess_text)

# Combine text
df["combined"] = df["name"] + " " + df["description"]

df.head()

def detect_lang_safe(text):
    try:
        return detect(text)
    except:
        return "unknown"

df["language"] = df["combined"].apply(detect_lang_safe)

df[["combined", "language"]].head()

model = SentenceTransformer('paraphrase-multilingual-MiniLM-L12-v2')

import numpy as np
texts = df["combined"].tolist()

embeddings = model.encode(texts, show_progress_bar=True)

print("Embeddings shape:", np.array(embeddings).shape)

cos_sim_matrix = cosine_similarity(embeddings)

def hybrid_score(text1, text2, emb_score):
    fuzz_score = fuzz.token_sort_ratio(text1, text2) / 100

    words1 = set(text1.split())
    words2 = set(text2.split())

    keyword_overlap = len(words1 & words2) / (len(words1) + 1e-5)

    final_score = (0.6 * emb_score) + (0.25 * fuzz_score) + (0.15 * keyword_overlap)

    return final_score

from sklearn.metrics.pairwise import cosine_similarity

# Already computed
cos_sim_matrix = cosine_similarity(embeddings)

# Get top K similar indices for each record
K = 10  # tune this

top_k_indices = np.argsort(-cos_sim_matrix, axis=1)[:, :K]

n = len(df)
hybrid_matrix = np.zeros((n, n))

for i in range(n):
    for j in top_k_indices[i]:
        if i == j:
            continue

        score = hybrid_score(
            df.iloc[i]["combined"],
            df.iloc[j]["combined"],
            cos_sim_matrix[i][j]
        )

        hybrid_matrix[i][j] = score
        hybrid_matrix[j][i] = score

import numpy as np

duplicates = []

# Calculate language-specific thresholds
language_thresholds = {}
unique_languages = df['language'].unique()
n = len(df) # total number of records

# Default threshold for languages not explicitly covered or for fallback
default_threshold = 0.80 # Keep a sane default if a language has too few samples

for lang in unique_languages:
    # Get indices for the current language
    lang_indices = df[df['language'] == lang].index.tolist()

    if len(lang_indices) < 2: # Cannot calculate meaningful scores if less than 2 items
        language_thresholds[lang] = default_threshold
        continue

    # Create a mask for efficient extraction from hybrid_matrix
    mask = np.zeros(n, dtype=bool)
    mask[lang_indices] = True

    # Extract the sub-matrix for items of this language
    # This gets scores for all pairs within the language
    lang_submatrix = hybrid_matrix[mask][:, mask]

    # Get upper triangle elements (excluding diagonal) to avoid self-comparison and duplicate pairs (i,j) and (j,i)
    lang_scores = lang_submatrix[np.triu_indices(len(lang_indices), k=1)].flatten()

    # Filter out zero scores as these indicate comparisons not made (due to K) or very low relevance
    meaningful_scores = lang_scores[lang_scores > 0]

    if len(meaningful_scores) > 0:
        # Set threshold as a high percentile (e.g., 90th) of *meaningful* scores within that language
        # This means roughly 10% of the most similar pairs within that language will be considered duplicates
        language_thresholds[lang] = np.percentile(meaningful_scores, 90)
    else:
        language_thresholds[lang] = default_threshold # Fallback to default if no meaningful scores

print("Language-specific thresholds:")
for lang, threshold_val in language_thresholds.items():
    print(f"- {lang}: {threshold_val:.4f}")

# Reset duplicates list
duplicates = []

for i in range(n):
    for j_idx in top_k_indices[i]: # Iterate only over top K similar items
        j = j_idx
        if i >= j: # Avoid self-comparison and duplicate pairs (i, j) vs (j, i)
            continue

        lang_i = df.iloc[i]["language"]
        lang_j = df.iloc[j]["language"]

        current_threshold = default_threshold # Start with default

        # Apply language-specific threshold if both items are of the same language
        if lang_i == lang_j and lang_i in language_thresholds:
            current_threshold = language_thresholds[lang_i]
        # Optional: Add logic for cross-language comparisons if desired, e.g.,
        # elif lang_i != lang_j:
        #     # Could take the average of thresholds or a stricter/looser common threshold
        #     current_threshold = (language_thresholds.get(lang_i, default_threshold) +
        #                          language_thresholds.get(lang_j, default_threshold)) / 2

        if hybrid_matrix[i][j] > current_threshold:
            duplicates.append((i, j, hybrid_matrix[i][j]))

print("\nTotal duplicates found with dynamic thresholds:", len(duplicates))
duplicates[:10]

def explain_match(i, j):
    t1 = df.iloc[i]["combined"]
    t2 = df.iloc[j]["combined"]

    emb_score = cos_sim_matrix[i][j]
    fuzz_score = fuzz.token_sort_ratio(t1, t2) / 100

    print(f"\nRecord {i} ↔ Record {j}")
    print("Text 1:", t1)
    print("Text 2:", t2)
    print(f"Semantic Score: {emb_score:.2f}")
    print(f"Fuzzy Score: {fuzz_score:.2f}")
    print(f"Final Score: {hybrid_matrix[i][j]:.2f}")

for d in duplicates[:5]:
    explain_match(d[0], d[1])

import networkx as nx

G = nx.Graph()

# Add nodes
for i in range(len(df)):
    G.add_node(i)

# Add edges for duplicates
for i, j, score in duplicates:
    G.add_edge(i, j, weight=score)

clusters = list(nx.connected_components(G))

# Filter only real duplicate groups
clusters = [c for c in clusters if len(c) > 1]

print("Total duplicate groups:", len(clusters))

for idx, cluster in enumerate(clusters):
    print(f"\n🔹 Group {idx}")
    for i in cluster:
        print("-", df.iloc[i]["combined"])

df["cluster"] = -1

for cluster_id, cluster in enumerate(clusters):
    for i in cluster:
        df.at[i, "cluster"] = cluster_id

df.to_csv("final_output.csv", index=False)

from google.colab import files
files.download("final_output.csv")

if "true_label" in df.columns:
    from sklearn.metrics import adjusted_rand_score

    score = adjusted_rand_score(df["true_label"], df["cluster"])
    print("Clustering Score:", score)

import pickle

with open("model.pkl", "wb") as f:
    pickle.dump(model, f)

# The variable 'vectorizer' was not defined. It seems you meant to save the 'model' here again, or a different object if a vectorizer was created.
# If you meant to save the 'model' instead of 'vectorizer', you can uncomment and modify the line below:
# with open("model_another_copy.pkl", "wb") as f:
#     pickle.dump(model, f)

files.download("model.pkl")
files.download("vectorizer.pkl")

"""### Current DataFrame Schema (Input and Output)"""

print('DataFrame Info (showing columns and data types):')
df.info()
print('\nFirst 5 rows of the DataFrame (showing sample data):')
display(df.head())

